export const IPC = {
  workspaceGet: 'workspace:get',
  workspaceRename: 'workspace:rename',
  settingsSave: 'settings:save',
  collectionSave: 'collection:save',
  collectionDelete: 'collection:delete',
  collectionExport: 'collection:export',
  envSave: 'env:save',
  envSetActive: 'env:setActive',
  httpSend: 'http:send',
  httpCancel: 'http:cancel',
  runsList: 'runs:list',
  runsGet: 'runs:get',
  runsSaveExample: 'runs:saveExample',
  runsAppended: 'runs:appended',
  transferExport: 'transfer:export',
  transferImport: 'transfer:import',
  profilesList: 'profiles:list',
  profilesCreate: 'profiles:create',
  profilesSwitch: 'profiles:switch',
  profilesRename: 'profiles:rename',
  profilesDelete: 'profiles:delete',
  shellOpenExternal: 'shell:openExternal'
} as const
